import type { Metadata } from "next";

import "./globals.css";

import { Anek_Gurmukhi } from 'next/font/google';

const anekGurmukhi = Anek_Gurmukhi({
  subsets: ['latin'],
  variable: '--font-anek-gurmukhi',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anekGurmukhi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
